(define (sqrt x)
	(define (sqrt-iter guess)
		(if (good-enough? guess)
			guess
			(sqrt-iter (improve guess) x)))
	(define (improve guess)
		(average guess (/ x guess)))
	(define (average x y)
		(/ (+ x y) 2))
	(define (good-enough? guess)
		(< (abs (- (square guess) x)) 0.001))
	(sqrt-iter 1.0))